name: Integration Tests

on: [ push, pull_request ]

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    environment: Azure-dev
    runs-on: ubuntu-latest
    steps:
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: 'Run Azure CLI commands'
        run: |
          az account show
          az group list
          pwd 

  Azure-Storage-Integration-Test:
    runs-on: ubuntu-latest

    env:
      RUN_INTEGRATION_TEST: true

    services:
      azurite:
        image: mcr.microsoft.com/azure-storage/azurite
        ports:
          - 10000:10000
        env:
          AZURITE_ACCOUNTS: account1:key1;account2:key2

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      - name: Data Plane Azure Storage Test
        run: ./gradlew extensions:azure:data-plane:storage:check

      - name: Data Plane Azure Data Factory Test
        run: ./gradlew extensions:azure:data-plane:data-factory:check

      - name: Object Storage StatusChecker Test
        run: ./gradlew extensions:azure:blobstorage:blob-provision:check
