name: Integration Tests

on: [ push, pull_request ]

permissions:
  id-token: write
  contents: read

jobs:
  check-env:
    environment: Azure-dev
    runs-on: ubuntu-latest
    steps:
      - id: has-azure
        env:
          FEATURE: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        if: "${{ env.FEATURE != '' }}"
        run: echo "::set-output name=defined::true"
    outputs:
      has-azure: ${{ steps.has-azure.outputs.defined }}

  Azure-Cloud-Integration-Test:
    needs: [ check-env ]
    if: needs.check-env.outputs.has-azure == 'true'
    environment: Azure-dev
    runs-on: ubuntu-latest

    env:
      RUN_INTEGRATION_TEST: true

    steps:
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: 'Run Azure CLI commands'
        run: |
          az account show
          az group list
          pwd 

      - uses: actions/checkout@v2

      - name: "terraform outputs"
        run: |
          printf "$CLOUD_SETTINGS" > cloud_settings.json
        env:
          CLOUD_SETTINGS: ${{ secrets.CLOUD_SETTINGS }}

      - name: "terraform outputs"
        run: |
          cat cloud_settings.json

      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      - name: Data Plane Azure Data Factory Test
        run: ./gradlew extensions:azure:data-plane:data-factory:test
