name: Integration Tests

on: [ push, pull_request ]

permissions:
  id-token: write
  contents: read

jobs:
  Azure-Cloud-Integration-Test:
    environment: Azure-dev
    runs-on: ubuntu-latest

    env:
      RUN_INTEGRATION_TEST: true

    steps:
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: 'Run Azure CLI commands'
        run: |
          az account show
          az group list
          pwd 

      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      - name: Data Plane Azure Data Factory Test
        run: ./gradlew extensions:azure:data-plane:data-factory:check