name: Integration Tests

on:
  push:

jobs:

  Azure-CosmosDB-Integration-Test:
    runs-on: windows-2019

    env:
      RUN_INTEGRATION_TEST: true

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Setup Gradle cache
        uses: gradle/gradle-build-action@v2

      - name: CosmosDB Transfer Process Store Test
        run: ./gradlew extensions:azure:cosmos:transfer-process-store-cosmos:compileTestJava

      - name: Cosmos-based Asset Index test
        run: ./gradlew extensions:azure:cosmos:assetindex-cosmos:compileTestJava

      - name: Cosmos-based FCN Directory test
        run: ./gradlew extensions:azure:cosmos:transfer-process-store-cosmos:compileTestJava

      - name: Cosmos-based ContractDefinitionStore Test
        run: ./gradlew extensions:azure:cosmos:contract-definition-store-cosmos:compileTestJava

      - name: Cosmos-based ContractNegotiationStore Test
        run: ./gradlew extensions:azure:cosmos:contract-negotiation-store-cosmos:compileTestJava